### ISSUE TITLE
doodledata.npy not found

### ISSUE THREAD

**Issue by h1455129980** [ankanbhunia/doodleformer#2]
please tell me how to load the file,thank you!

**Comment by ConAct** [comment]
Having the same issue. Apparently it's not included in the git repository nor the dataset download from google drive.

**Comment by ankanbhunia** [comment]
You can use the data_process.py file to create those files directly from the raw data. Alternatively, you can use the following drive links:

https://drive.google.com/file/d/1tsGaN0AOtGO5ba8BseGVIfQLVTs92ErR/view?usp=share_link
https://drive.google.com/file/d/1YB4FkkzoRuUqxcXcEzqDc7JVsvP370rT/view?usp=share_link
